export const IP_LOCATION_CHECK_API_ACCESS_KEY = process.env.NEXT_PUBLIC_IP_LOCATION_CHECK_API_ACCESS_KEY || '';
export const WEATHER_DATA_API_ACCESS_KEY = process.env.NEXT_PUBLIC_WEATHER_API_ACCESS_KEY || '';
